package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.notifications
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'A_A'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("A_A")) {
    features {
        add {
            notifications {
                notifierSettings = slackNotifier {
                    connection = "PROJECT_EXT_3"
                    sendTo = "teamcity"
                    messageFormat = simpleMessageFormat()
                }
            }
        }
    }
}
