package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Buildsplit'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Buildsplit")) {
    cleanup {
        expect {
            keepRule {
                id = "KEEP_RULE_6"
                keepAtLeast = builds(2)
                applyToBuilds {
                    withStatus = successful()
                }
                dataToKeep = everything()
                preserveArtifactsDependencies = true
            }
        }
        update {
            keepRule {
                id = "KEEP_RULE_6"
                keepAtLeast = builds(2)
                dataToKeep = everything()
                preserveArtifactsDependencies = true
            }
        }
    }
}
