package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildGradle'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildGradle")) {
    expectSteps {
        gradle {
            tasks = "buildDependents"
            incremental = true
            useGradleWrapper = true
            enableDebug = true
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            clearConditions()
            tasks = "clean build"
            incremental = false
            gradleWrapperPath = ""
            enableDebug = false
            param("teamcity.coverage.idea.includePatterns", "")
            param("teamcity.coverage.jacoco.patterns", "")
            param("teamcity.coverage.emma.instr.parameters", "")
            param("teamcity.coverage.emma.include.source", "")
            param("teamcity.tool.jacoco", "")
        }
    }
}
