package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildGradle'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildGradle")) {
    expectSteps {
        gradle {
            tasks = "buildDependents"
            incremental = true
            useGradleWrapper = true
            enableDebug = true
        }
    }
    steps {
        items.removeAt(0)
    }
}
