package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.parallelTests
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Cba'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Cba")) {
    params {
        expect {
            param("aa", "master")
        }
        update {
            param("aa", "master2")
        }
    }

    vcs {
        expectEntry(DslContext.settingsRoot.id!!, "-:.idea", "-:manyfiles")
        root(DslContext.settingsRoot.id!!)
    }

    features {
        remove {
            parallelTests {
                numberOfBatches = 3
            }
        }
    }
}
