package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Cba'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Cba")) {
    params {
        expect {
            param("aa", "an")
        }
        update {
            param("aa", "master")
        }
        add {
            param("env.env", "envmaster")
        }
        add {
            password("parsec", "credentialsJSON:a42e2243-4440-4b74-a541-65893bb2c686")
        }
    }

    expectSteps {
        gradle {
            tasks = "clean build"
            gradleWrapperPath = ""
        }
    }
    steps {
        insert(1) {
            script {
                executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
                scriptContent = "echo master"
            }
        }
        insert(2) {
            script {
                name = "New build step"
                executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
                scriptContent = "echo %parsec% > parsec.txt"
            }
        }
    }

    requirements {
        add {
            contains("teamcity.agent.name", "Default")
        }
    }
}
