package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Comp'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Comp")) {
    dependencies {
        remove(AbsoluteId("Gradle_Gradle")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
            }
        }

        add(RelativeId("Gradle")) {
            snapshot {
                reuseBuilds = ReuseBuilds.ANY
            }
        }

    }
}
