package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Gradle'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Gradle")) {
    expectSteps {
        gradle {
            tasks = "clean build"
            gradleWrapperPath = ""
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            clearConditions()
            param("ui.gradleRUnner.gradle.build.file", "jhgjhg")
        }
    }
}
