package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup_Splitgradle'
in the project with id = 'HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup', and delete the patch script.
*/
create(RelativeId("HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup"), BuildType({
    id("HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup_Splitgradle")
    name = "splitgradle"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        gradle {
            tasks = "clean build"
            gradleWrapperPath = ""
        }
    }

    features {
        feature {
            type = "splitTests"
            param("numberOfParts", "3")
        }
    }
}))

