package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.BuildCacheFeature
import jetbrains.buildServer.configs.kotlin.buildFeatures.buildCache
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Maven_BuildFeature'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Maven_BuildFeature")) {
    features {
        val feature1 = find<BuildCacheFeature> {
            buildCache {
                name = "mavenCache"
                use = false
                publishOnlyChanged = false
                rules = ".m2"
            }
        }
        feature1.apply {
            use = true
        }
    }
}
