package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PingHost'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PingHost")) {
    expectSteps {
        script {
            scriptContent = "echo a > a.txt"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                echo a > a.txt
                exit 1
            """.trimIndent()
        }
    }
}
