package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publisher'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publisher")) {
    dependencies {
        expect(RelativeId("LookAndFeel")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "lib/svgviewer.zip=>External-Artifacts/output/TeamCity-Artifacts/LookAndFeel"
            }
        }
        update(RelativeId("LookAndFeel")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "**/*=>External-Artifacts/output/TeamCity-Artifacts/LookAndFeel"
            }
        }

    }
}
