package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.AmazonEC2CloudImage
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.amazonEC2CloudImage
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<AmazonEC2CloudImage> {
            amazonEC2CloudImage {
                id = "PROJECT_EXT_10"
                profileId = "amazon-10001"
                name = "im4"
                vpcSubnetId = "subnet-0ace2a91ee63119ea"
                keyPairName = "chubatova-amazon-ireland"
                instanceType = "t3.medium"
                securityGroups = listOf("sg-072d8bfa0626ea2a6")
                source = Source("i-070d9dd2e2f4f3a6e")
            }
        }
        feature1.apply {
            profileId = "amazon-10001"
            agentPoolId = "-2"
            name = "im4"
            vpcSubnetId = "subnet-0ace2a91ee63119ea"
            keyPairName = "chubatova-amazon-ireland"
            instanceType = "t3.medium"
            securityGroups = listOf("sg-072d8bfa0626ea2a6")
            source = Source("i-070d9dd2e2f4f3a6e")
        }
    }
}
