package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.slackConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'A'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("A")) {
    features {
        add {
            slackConnection {
                id = "PROJECT_EXT_3"
                displayName = "Slack"
                botToken = "credentialsJSON:928261c6-7bef-4ea9-9ca5-3fa9150a6528"
                clientId = "asd"
                clientSecret = "credentialsJSON:6f7da4d2-4c3e-4173-a57b-9bd78dc801a5"
            }
        }
    }
}
