package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Project({
    id("HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup")
    name = "https://github.com/ChubatovaTiger/ChubatovaGradleTestsBackup"

    cleanup {
        baseRule {
            all(builds = 2)
        }
    }
}))

